baseURL = "https://MoCI-L.github.io/MoCI-tech-site/"
languageCode = "zh-cn"
title = "MoCI Tech Site"
theme = "PaperMod"

[pagination]
  pagerSize = 10


[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  author = "MoCI"
  ShowReadingTime = true
  defaultTheme = "auto"
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = true
  ShowPostNavLinks = true
  EnableRSS = true
  ShowLastMod = true
  ShowCategories = true
  ShowTags = true
  ShowPageShare = true
  ShowSocialIcons = true
  #开启搜索
  SearchEngine = "lunr"
  ShowMenuSearch = true
[params.social]
  github = "https://github.com/MoCI-L"
  email = "example@email.com"
  telegram = "https://t.me/YourTelegram"
  rss = "/index.xml"

[params.header]
  showTitle = true
  sticky = true
  showMenu = true
[menu]
  [[menu.main]]
      identifier = "about"
      name = "关于"
      url = "/about/"
      weight = 5
  [[menu.main]]
      identifier = "posts"
      name = "文章"
      url = "/posts/"
      weight = 10

  [[menu.main]]
      identifier = "notes"
      name = "笔记"
      url = "/notes/"
      weight = 20

  [[menu.main]]
      identifier = "files"
      name = "资料"
      url = "/files/"
      weight = 30

[markup]
  [markup.highlight]
    style = "dracula"
    lineNumbers = true
    noClasses = false
